### ISSUE TITLE
Headless Server?

### ISSUE THREAD

**Issue by drguildo** [weavejester/compojure-example#7]
Maybe it would be better to use `lein ring server-headless` to run the server as I imagine most people will be running this from a terminal.

When I ran it using `lein ring server` I get:

```
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:181)
        at clojure.java.browse_ui$open_url_in_swing.invoke(browse_ui.clj:20)
        at clojure.lang.Var.invoke(Var.java:415)
        at clojure.java.browse$open_url_in_swing.invoke(browse.clj:44)
        at clojure.java.browse$browse_url.invoke(browse.clj:52)
        at ring.server.standalone$open_browser_to.invoke(standalone.clj:39)
        at ring.server.standalone$serve$fn__1506.invoke(standalone.clj:102)
        at ring.server.standalone$try_port.invoke(standalone.clj:16)
        at ring.server.standalone$serve.doInvoke(standalone.clj:95)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at ring.server.leiningen$serve.invoke(leiningen.clj:20)
        at user$eval2054.invoke(form-init2066820887519135966.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6511)
        at clojure.lang.Compiler.eval(Compiler.java:6501)
        at clojure.lang.Compiler.load(Compiler.java:6952)
        at clojure.lang.Compiler.loadFile(Compiler.java:6912)
        at clojure.main$load_script.invoke(main.clj:283)
        at clojure.main$init_opt.invoke(main.clj:288)
        at clojure.main$initialize.invoke(main.clj:316)
        at clojure.main$null_opt.invoke(main.clj:349)
        at clojure.main$main.doInvoke(main.clj:427)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
```

**Comment by weavejester** [comment]
I'm pretty sure the majority of programmers develop in graphical operating systems. Text-only development environments certainly exist, but they're used by a pretty small minority.

You can turn off the browser communication by setting the `:open-browser?` option to false, e.g.

``` clojure
:ring {:open-browser? false}
```

If you have a text-only development environment, you can set this in your `$HOME/.lein/profiles.clj` file to force it globally.

**Comment by drguildo** [comment]
Fair point. As an aside, the URL for Ring in the README should be updated to point to https://github.com/ring-clojure/ring.

**Comment by weavejester** [comment]
The repo's a couple of years out of date, so all the links and dependencies are old. I might retire the repository in favour of a more specific and modern example.
